<?php
/**
 * AJAX Thickbox Plugin
 *
 * @see http://drupal.org/project/ajax
 * @see irc://freenode.net/#drupy
 * @depends Drupal 6
 * @author brendoncrawford
 * @note This file uses a 79 character width limit.
 *
 */

/**
 * Implementation of hook_preprocess_hook().
 *
 * @param variables Assoc
 * @return Bool
 *
 */
function ajax_disable_redirect_preprocess_page(&$variables) {
  drupal_add_js(drupal_get_path('module', 'ajax_disable_redirect') .
    '/ajax_disable_redirect.js', 'theme');
  return TRUE;
}

/**
 * Ajax admin options callback
 */
function ajax_disable_redirect_ajax_options(&$options) {
  $options['disable_redirect'] = array(
    '#value' => t('Disable Redirect')
  );
  $options['remove_form'] = array(
    '#value' => t('Remove Form After Submit')
  );
  return TRUE;
 }
 
 function ajax_disable_redirect_menu() {
 	$items = array();
 	$items['ajax_webform'] = array(
 	    'title' => 'Ajax handler',
 	    'page callback' => 'ajax_disable_redirect_get_response',
 	    'access arguments' => array('access content'),
 	    'type' => MENU_CALLBACK,
   	);
   	return $items;
 }
 
 function ajax_disable_redirect_get_response() {
 	$path = $_GET["url"];
 	if ($path) {
 		$path = explode('/', str_replace('http://', '', $path));
 		module_invoke('webform');
 		$response = _webform_confirmation(node_load($path[2]));
 		print drupal_json(array('content' => $response));
 	}
 	exit();
}