<?php
function colorbox_webform_menu() {
  $items = array();

  $items['colorbox/webform'] = array(
    'title' => 'Webform',
    'page callback' => 'colorbox_webform_page',
    'page arguments' => array(2),
    'access callback' => '_colorbox_webform_page_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Colorbox menu access check.
 */
function _colorbox_webform_page_access($form_id) {
	return node_access('view', node_load($form_id));
}



/**
 * Menu callback for colorbox_webform_page.
 */
function colorbox_webform_page($form_id) {
  $GLOBALS['devel_shutdown'] = FALSE; // Prevent devel module from spewing.
  
	$node = node_load($form_id);
	
  	//$form = drupal_get_form("webform_client_form_$form_id", $node, array(), false, false);
	
	node_build_content($node);
	$form = drupal_render($node->content);
	
	print $form;

  exit;
}