<?php
// $Id: domain_blocks.module,v 1.1.2.5 2010/04/05 17:41:06 nonsie Exp $

/**
 * @file
 * Provides domain specific visibility settings for blocks based on domain
 * access settings. Domain Blocks does not define any permissions of its own
 * yet it requires user to have "set domain access permission" in order to
 * define any domain based visibility settings.
 */

/**
 * Implementation of hook_help().
 * Display help and module information
 * @param string $path
 * which path of the site we're displaying help
 * @param array $arg
 * array that holds the current path as would be returned from arg() function
 * @return string
 * help text for the path
 */
function domain_blocks_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#domain_blocks":
      $output = '<p>'.  t("Provides domain specific visibility settings for blocks") .'</p>';
      break;
  }
  return $output;
}

/**
 * Save domain block data
 * @param string $module
 * @param string $delta
 * @param array $current_domains
 * @param array $previous_domains
 */
function domain_blocks_save($module, $delta, $current_domains, $previous_domains) {
  // None of the domains are checked
  if (empty($current_domains)) {
    // Previously some domains were checked
    if (!empty($previous_domains)) {
      db_query("DELETE FROM {domain_blocks} WHERE module = '%s' AND delta = '%s'", $module, $delta);
      // Block is now visible on all domains (domain_site grant)
      $realm = 'domain_site';
      db_query("INSERT INTO {domain_blocks} (module, delta, realm, domain_id) VALUES ('%s', '%s', '%s', %d)", $module, $delta, $realm, 0);
    } 
    // No domains were previously checked.
    elseif (!isset($previous_domains)) {
      // Block is now visible on all domains (domain_site grant)
      $realm = 'domain_site';
      db_query("INSERT INTO {domain_blocks} (module, delta, realm, domain_id) VALUES('%s', '%s', '%s', %d)", $module, $delta, $realm, 0);
    }
  }
  else {
    // No domains were previously checked
    if (empty($previous_domains)) {
      // Remove domain_site grant - block visibility is defined by individual domains
      $realm = 'domain_site';
      db_query("DELETE FROM {domain_blocks} WHERE module = '%s' AND delta = '%s' AND realm = '%s'", $module, $delta, $realm);
      // Insert all domains selected
      $realm = 'domain_id';
      foreach ($current_domains as $single_domain_id) {
        db_query("INSERT INTO {domain_blocks} (module, delta, realm, domain_id) VALUES ('%s', '%s', '%s', %d)", $module, $delta, $realm, $single_domain_id);
      }
    }
    else {
      // Previously some domains were checked and now some domains are checked.
      // Unset previously checked values that are now unchecked
      $domains_to_be_removed = array_diff($previous_domains, $current_domains);
      if (!empty($domains_to_be_removed)) {
        $domains_to_be_removed = implode(',', $domains_to_be_removed);
        $realm = 'domain_id';
        if (isset($domains_to_be_removed)) {
          db_query("DELETE FROM {domain_blocks} WHERE module = '%s' AND delta = '%s' AND realm = '%s' AND domain_id IN (%s)", $module, $delta, $realm, $domains_to_be_removed);
        }
      }
      // Set new values, now checked and previously not checked
      $domains_to_add = array_diff($current_domains, $previous_domains);
      if (!empty($domains_to_add)) {
        $realm = 'domain_id';
        foreach ($domains_to_add as $single_domain_id) {
          db_query("INSERT INTO {domain_blocks} (module, delta, realm, domain_id) VALUES ('%s', '%s', '%s', %d)", $module, $delta, $realm, $single_domain_id);
        }
      }
    }
  }
}

/**
 * Implementation of block form_alter().
 */
function domain_blocks_form_alter(&$form, $form_state, $form_id) {
  if (($form_id == 'block_admin_configure' || $form_id == 'block_box_form' || $form_id == 'block_add_block_form')) {
    // If the user is a site admin, show the form, otherwise pass it silently.
    if (user_access('set domain access')) {
      $module = $form['module']['#value'];
      $delta = $form['delta']['#value'];
      $form['domain_vis_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Domain specific visibility settings'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#weight' => 0,
      );
      $previous_block_domains = _domain_blocks_load($module, $delta);
      $block_domains = array();
      if (count($previous_block_domains) > 0) {
        foreach ($previous_block_domains as $value) {
          $value == 0 ? $value = -1 : $value = $value;
          $block_domains[] = $value;
        }
      }
      $options = array();
      foreach (domain_domains() as $data) {
        // Cannot pass zero in checkboxes.
        ($data['domain_id'] == 0) ? $key = -1 : $key = $data['domain_id'];
        // The domain must be valid or accessible for the current user
        if ($data['valid'] || user_access('administer domains') || user_access('access inactive domains')) {
          $options[$key] = $data['sitename'];
        }
      }
      $form['domain_vis_settings']['domain_blocks'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Display on'),
        '#options' => $options,
        '#required' => FALSE,
        '#description' => t('Limit block display to these affiliates. This block is visible on all domains by default using this theme.'),
        '#default_value' => $block_domains,
      );
      $form['domain_vis_settings']['previous_domain_blocks'] = array(
        '#type' => 'value',
        '#value' => $previous_block_domains,
      );
      $form['#submit'][] = 'domain_blocks_form_submit';
    }
  }
  // Submit handler for user defined block deletion
  if ($form_id == 'block_box_delete') {
    $form['#submit'][] = 'domain_blocks_delete_submit';
  }
  // Blocks overview form submit
  if ($form_id == 'block_admin_display_form') {
    $form['#submit'][] = 'domain_blocks_admin_display_submit';
  }
}

/**
 * Forms api callback. Submit function
 */
function domain_blocks_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  // Delta may be zero for other modules than block.
  if (!$values['delta'] && $values['module'] == 'block') {
    $values['delta'] = db_result(db_query("SELECT MAX(bid) FROM {boxes}"));
  }
  $enabled_domains = array();
  if (!empty($values['domain_blocks'])) {
    foreach ($values['domain_blocks'] as $single_domain_id => $domain_enabled) {
      if ($domain_enabled) {
        if ($single_domain_id == -1) {
          $single_domain_id = 0;
        }
        $enabled_domains[] = $single_domain_id;
      }
    }
  }
  domain_blocks_save($values['module'], $values['delta'], $enabled_domains, $values['previous_domain_blocks']);
}

/**
 * Submit handler for user defined block deletion
 */
function domain_blocks_delete_submit($form, &$form_state) {
  db_query("DELETE FROM {domain_blocks} WHERE module = 'block' AND delta = '%s'", $form_state['values']['bid']);
}

/**
 * Grant domain_site permission when there are new previously disabled blocks
 * or blocks without any grants on main blocks administration form submission.
 */
function domain_blocks_admin_display_submit($form, &$form_state) {
  $new_blocks = db_query("SELECT DISTINCT b.module, b.delta FROM {blocks} b LEFT JOIN {domain_blocks} db ON (b.module = db.module AND b.delta = db.delta) WHERE db.module IS NULL");
  while ($block = db_fetch_object($new_blocks)) {
    db_query("INSERT INTO {domain_blocks} (module, delta, realm, domain_id) VALUES ('%s', '%s', '%s', %d)", $block->module, $block->delta, 'domain_site', 0);
  }
}

/**
 * Implementation of hook_db_rewrite_sql().
 */
function domain_blocks_db_rewrite_sql($query, $primary_table, $primary_key, $args) {
  global $_domain;
  if ($primary_table == 'b' && $primary_key == 'bid') {
    $result['join'] .= " INNER JOIN {domain_blocks} db ON db.module = b.module ";
    $result['where'] .= " db.delta = b.delta ";
    $result['where'] .= " AND ((db.realm = 'domain_site' AND db.domain_id = 0) OR (db.realm = 'domain_id' AND db.domain_id = ". $_domain['domain_id'] ."))";
    return $result;
  }
}

/**
 * Look up domain blocks based on block module and delta
 *
 * @param string $module
 * @param string $delta
 * @return array
 */
function _domain_blocks_domain_lookup($module = NULL, $delta = NULL) {
  $result = array();
  if (!is_null($module) && !is_null($delta)) {
    $result = db_fetch_array(db_query("SELECT domain_id from {domain_blocks} WHERE module = '%s' AND delta = '%s'", $module, $delta));
  }
  return $result;
}

/**
 * Returns block visibility.
 * NULL if not available, array() if using domain_site grant, keyed array if
 * using domain_id grant(s).
 * @param string $module
 * @param int $delta
 */
function _domain_blocks_load($module, $delta) {
  $result = db_query("SELECT domain_id, realm FROM {domain_blocks} WHERE module = '%s' AND delta = '%s'", $module, $delta);
  while ($row = db_fetch_array($result)) {
    $block[$row['realm']][] = $row['domain_id'];
  }
  if (isset($block['domain_site'])) {
    return array();
  }
  return $block['domain_id'];
}

/**
 * Implementation of hook_domainupdate().
 */
function domain_blocks_domainupdate($op, $domain, $edit = array()) {
  switch ($op) {
    case 'delete':
      // remove records
      _domain_blocks_delete($domain);
    case 'update':
    case 'insert':
    default:
    break;
  }
}

function _domain_blocks_delete($domain) {
  db_query("DELETE FROM {domain_blocks} WHERE domain_id = %d AND realm = 'domain_id'", $domain['domain_id']);
}
