<?php
	
	/**
	 * Implementation of hook_menu().
	 */
	function ue_faves_menu()
	{
		$items = array();
		
		$items['user/%/favorites'] = array(
			'title' => 'Favorites',
			'description' => 'Favorites',
			'page callback' => 'ue_faves_user_faves',
			'access callback' => 'ue_custom_user_logged_access',
			'type' => MENU_LOCAL_TASK
		);
		
		return $items;
	}
	
	function ue_faves_user_faves()
	{
		global $user;
		
		drupal_set_title(t('Favorites'));
		
		return views_embed_view('saved_nodes', 'default');
	}