<?php

/**
 * Impletementation of hook_form_alter().
 */
function blvd_east_helper_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_register':
      $form['fbconnect_button']['#description'] = '';
      $form['fbconnect_button_separater'] = array(
        '#value' => t('<fieldset class=\'no-borders\'><legend>OR</legend></fieldset>'),
        '#weight' => '-99',
      );
      $form['account']['#title'] = t('Create a FREE account or ' . l(t('login'), 'user/login') . ' to post a listing');
      break;
  }
}

