<?php
	
	/**
	 * Implementation of hook_menu().
	 */
	function ue_internal_reports_menu()
	{
		$items = array();
		
		$items['admin/reports/internal'] = array(
			'title' => 'Internal Reports',
			'description' => 'Internal Reports',
			'page callback' => 'ue_internal_reports_page_reports',
			'access arguments' => array('filter and manage site content'),
		);
		
		return $items;
	}
	
	function ue_internal_reports_page_reports()
	{
		return theme('item_list', array(
			l('properties marked manhattan', 'internal_reports/neigh_buildings'),
			l('buildings with addr, neigh; sorted by addr1', 'internal_reports/buildings'),
			l('owners/managers', 'internal_reports/companies'),
			l('duplicates', 'internal_reports/dupes'),
			l('building optimization', 'internal_reports/property_optimization'),
			l('manage all', 'internal_reports/manage_all'),
			l('manage all: content update', 'internal_reports/content_update'),
			l('two weeks old', 'internal_reports/two_weeks_old'),
			l('user list', 'internal_reports/user_list'),
			l('buildings with no contact info', 'internal_reports/without_contact'),
			l('google locations', 'internal_reports/google_locations'),
		));
	}